require:
  - rubocop-ordered_methods
  - rubocop-yard

plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
  AllowSteepAnnotation: true
  Exclude:
    - bin/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
  Max: 500

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
  Max: 100

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call
  Max: 500

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/IncludeExamples:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma

ThreadSafety:
  Exclude:
    - bin/**/*
    - '*.gemspec'

ThreadSafety/ClassInstanceVariable:
  Enabled: false